### ISSUE TITLE
为什么搭建好后，什么都没有呢？cookie是通过方式二获取的。

### ISSUE THREAD

**Issue by tankangy** [ellermister/mybili#25]
![image](https://github.com/user-attachments/assets/3d47b86c-de5c-4d66-9170-02c9353a6039)
查看任务报403。
![image](https://github.com/user-attachments/assets/d1deccc9-4762-4f68-a504-63f31b0d2126)
麻烦大佬看一下。感谢！！

**Comment by tankangy** [comment]
查看/var/log/下的日志文件，没有报错。

**Comment by tankangy** [comment]
![image](https://github.com/user-attachments/assets/1683dead-b625-4a3f-a58f-292612af89d7)
![image](https://github.com/user-attachments/assets/f261b54a-c903-41d0-bebe-afadb00c6885)
![image](https://github.com/user-attachments/assets/a195f600-cf85-4feb-be24-269a39c34a08)
![image](https://github.com/user-attachments/assets/177b5e79-f6f1-45f6-96bc-b3fa44a422b7)
![image](https://github.com/user-attachments/assets/b9b80250-f792-4641-aac9-47e4f2805d51)
4个日志文件，好像是没有报错信息。

**Comment by ellermister** [comment]
我觉得你的配置文件可能存在问题，你再看下这个日志
```
/app/storage/logs/laravel.log
```

**Comment by tankangy** [comment]
> 我觉得你的配置文件可能存在问题，你再看下这个日志
> 
> ```
> /app/storage/logs/laravel.log
> ```

![image](https://github.com/user-attachments/assets/914eb94f-2dec-42c0-8f5a-7f7887df1f94)
该目录下没有相关的log.

**Comment by tankangy** [comment]
![image](https://github.com/user-attachments/assets/c1dc98c3-8b74-41f9-84b6-ccdf574a8905)
整个docker中都没有这个laravel.log文件。docker构建按github中的复制的。

**Comment by ellermister** [comment]
1. 不清楚你是怎么建立的容器，你可以把创建容器的命令或者 compose.yml 配置完整粘贴出来吗？

2. 另外你可以尝试下给存储目录赋予 777 权限以测试是否是权限不足导致的，虽然理论已经是执行者root且目录权限对了，不知道是不是文件系统有一些奇怪的问题? 你的宿主机有什么特殊的设置吗？
```
chmod -R 777 /app/storage/

#再重启容器
```

3. 还有项目根目录 .env 文件，你可以粘贴展示下内容
```
cat  /app/.env
```

**Comment by XiaosongWen** [comment]
你好@ellermister我有类似的问题，cookie检测有效，但是progress显示NaN 没有laravel.log, 配置用的都是readme里面的配置

.env:
```
APP_KEY=base64:1CJOuWliDyx0ZBIZyn0gRKOOOq6+23YG/UHcUP4ffaU=
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_DB=3
REDIS_PREFIX=
```
docker-compose.yaml:
```
services: 
    mybili:
        image: ellermister/mybili
        ports:
            - "5151:80"
        volumes:
            - "./data:/app/storage/app/public"
            - "./.env:/app/.env"
            - "./cookie.txt:/app/storage/app/cookie.txt"
    redis:
        image: redis
        volumes:
            - "./redis:/data"
        command: redis-server --save 60 1 --loglevel warning  
```
我用的是Windows11，多谢了
