### ISSUE TITLE
群晖部署后无法访问

### ISSUE THREAD

**Issue by phantasy36** [ellermister/mybili#37]
一、群晖部署脚本如下：
services: 
    mybili:
        image: ellermister/mybili
        ports:
            - "5151:80"
        volumes:
            - "/volume1/Downloads/mybili:/app/storage/app/public"
            - db-data:/data

        environment:
            REDIS_HOST: redis
            REDIS_DB: 3
            DB_CONNECTION: sqlite
            DB_DATABASE: /volume5/docker/mybili/database.sqlite
    redis:
        image: redis
        volumes:
            - redis-data:/data
        command: redis-server --save 60 1 --loglevel warning

volumes:
  db-data:
  redis-data:

二、前端日志如下：
No log line matching the '' filter

三、redis日志如下：
Starting Redis Server

1:C 23 Jun 2025 11:50:50.263 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

1:M 23 Jun 2025 11:50:50.265 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

四、访问页面如下：

![Image](https://github.com/user-attachments/assets/50ac13ef-810f-49ea-8ec7-4bfc392599e3)

五、群晖配置如下：

<img width="670" alt="Image" src="https://github.com/user-attachments/assets/96166140-6f27-4707-ba7a-d205c65dddc0" />

**Comment by ellermister** [comment]
是不是redis没有正确启动或者是 mybili 容器无法连接到 redis。
1. 检查 redis 进程是否存在，redis 容器内部使用 redis-cli 进行测试连接。
2. 在 mybili 容器内部使用curl redis:6379 -vvl 看能否有连通的迹象。

**Comment by phantasy36** [comment]
1、redis 容器内部使用 redis-cli 

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/b42a844d-aa28-4899-8a56-10fcd7136861" />

2、在 mybili 容器内部使用curl redis:6379 -vvl 

<img width="458" alt="Image" src="https://github.com/user-attachments/assets/aff8d7e2-a88c-410c-a7db-f677aaf25b5b" />

**Comment by phantasy36** [comment]
> 没有看到明显的问题，你尝试看这个日志文件有没有报错的详情栈链，看是哪里触发了这个超时bug 容器内：/app/storage/logs/laravel.log

<img width="1084" alt="Image" src="https://github.com/user-attachments/assets/b1a95396-eb21-47b0-81df-05eeed07d5c7" />

**Comment by ellermister** [comment]
这里日志显示就是redis连接超时报错, 我总觉得你的 redis 部署有问题。

你需要在 redis 容器内 redis-cli 连接后，随便写点数据看是否能正确保保存
```
redis-cli
set aaa bbb
save
```
如果没问题， 你再把 redis 的端口映射出来，通过固定IP连接。参数参考：
```
services: 
    mybili:
        image: ellermister/mybili
        ports:
            - "5151:80"
        volumes:
            - "./data:/app/storage/app/public"
            - db-data:/data

        environment:
            REDIS_HOST: 你nas的IP
            REDIS_DB: 3
            DB_CONNECTION: sqlite
            DB_DATABASE: /data/database.sqlite
    redis:
        image: redis
        ports:
          - "6379:6379"
        volumes:
            - redis-data:/data
        command: redis-server --save 60 1 --loglevel warning

volumes:
  db-data:
  redis-data:
```

如果还没解决，若你有其他可用的 redis 服务，也可以把环境变量中的 redis 相关配置改掉试试。

**Comment by phantasy36** [comment]
> 如果还没解决，若你有其他可用的 redis 服务，也可以把环境变量中的 redis 相关配置改掉试试。

我没有其他redis服务。

**Comment by ellermister** [comment]
你按最新的方法测试了吗，redis能否写入保存数据

**Comment by ellermister** [comment]
```
DB_DATABASE: /volume5/docker/mybili/database.sqlite
```
你的这个配置应该是错误，检查这个路径是否存在，建议先复制一份推荐的配置。在此基础上修改。
```
services: 
    mybili:
        image: ellermister/mybili
        ports:
            - "5151:80"
        volumes:
            - "./data:/app/storage/app/public"
            - db-data:/data

        environment:
            REDIS_HOST: redis
            REDIS_DB: 3
            DB_CONNECTION: sqlite
            DB_DATABASE: /data/database.sqlite
    redis:
        image: redis
        volumes:
            - redis-data:/data
        command: redis-server --save 60 1 --loglevel warning

volumes:
  db-data:
  redis-data:
```

如果要修改路径，你应该要确认只修改volume中的映射，且是 : 冒号左边的才是宿主机，右侧是容器内不应该被修改，
